# Exploratory Data Analysis (EDA) – Opportunity Dataset

This notebook contains the complete Exploratory Data Analysis (EDA) workflow for the Opportunity Dataset, implemented using **Python, Pandas, and NumPy**.

**Note:** Visualizations are intentionally excluded from this notebook, as they are documented separately in the accompanying **Visualization Report** to avoid duplication.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("Opportunity_Analysis_Ready (2).xlsx")

print("Dataset Loaded Successfully!")

NameError: name 'pd' is not defined

In [ ]:
# Shape

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 5730
Columns : 20

**Basic Dataset Information**

In [ ]:
# Column Names

df.columns.tolist()

['opportunity_id',
 'category',
 'code',
 'created_at',
 'currency_type',
 'duration',
 'duration_type',
 'fee',
 'image_link',
 'is_archived',
 'is_auto_approve',
 'last_date_to_apply',
 'location',
 'long_description',
 'microscholarship',
 'modified_at',
 'name',
 'role',
 'role_responsibility',
 'short_description']

In [ ]:
# First Five Rows

df.head()

,opportunity_id,category,code,created_at,currency_type,duration,duration_type,fee,image_link,is_archived,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,role,role_responsibility,short_description
0,Opportunity#000000000GBD0AX3Z6VYRG7R75,Competition,M636023,2022-08-08 23:06:40,USD,300.0,minutes,0.0,https://www.clipartkey.com/mpngs/m/56-563364_b...,1.0,1.0,2023-07-22 04:26:40,NaN,"Your future is in your hands, truly. Ideate an...",500.0,2023-07-22 04:26:40,Mini Saga 3.0,NaN,NaN,Express yourself in 50-words!
1,Opportunity#000000000GFKZ4N696ZF8V2WM8,Career,A463411,2022-08-08 23:06:40,USD,1.0,years,0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,1.0,1.0,2023-07-22 04:26:40,NaN,At GlobalShala we believe that experiential le...,100.0,2023-07-22 04:26:40,Virtual Internship Facilitator,Facilitator,Leading and mentoring a group of 5-10 students...,In this role you be impacting young lives whil...
2,Opportunity#0000000010ZFE0ZS22FA3Q62R4,Career,A8848RT,2024-03-09 16:00:00,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,0.0,2019-06-08 13:20:00,Work From Home,NaN,0.0,2024-03-09 16:00:00,Careerwishlist Automation 1710333189352,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ..."
3,Opportunity#000000000GG34EPWZAJ6BDPQKP,Internship,I882052,2022-12-02 16:53:20,USD,20.0,minutes,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,1.0,1.0,2023-11-14 22:13:20,NaN,"In this internship, you will help your sponsor...",1000.0,2023-07-22 04:26:40,Digital Marketing - Demo,Social Media Analyst,NaN,Explore the best practices and proven strategi...
4,Opportunity#000000000GQHDFWJ9R1HQJ4WTE,Event,E307640,2022-08-08 23:06:40,USD,3.0,years,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,0.0,1.0,2026-05-28 20:26:40,NaN,As technologies such as social media apps and ...,500.0,2026-05-28 20:26:40,Humanizing Technology: An Introduction to User...,NaN,NaN,Students will learn the fundamentals of user e...

In [ ]:
# Last Five Rows

df.tail()

,opportunity_id,category,code,created_at,currency_type,duration,duration_type,fee,image_link,is_archived,is_auto_approve,last_date_to_apply,location,long_description,microscholarship,modified_at,name,role,role_responsibility,short_description
5725,Opportunity#0000000010ZWDN5F2Z2G6CH9VN,Career,AX9ARWF,2023-11-14 22:13:20,USD,2.0,months,0.0,ssdcd,NaN,1.0,2023-11-14 22:13:20,Virtual,sdfvrgfv,1111.0,2023-11-14 22:13:20,career test opportunity,NaN,cdc,sdvfrgfv
5726,Opportunity#0000000010VRW600T7H5AXZJ10,Internship,IJ0J8MZ,2025-10-09 08:53:20,INR,1.0,months,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,0.0,2025-10-09 08:53:20,Virtual,Long,0.0,2025-10-09 08:53:20,Rej,R,NaN,Short
5727,Opportunity#0000000010VS9RA65P8D1FA5ZE,Career,A3URJDB,2024-03-09 16:00:00,USD,30.0,weeks,1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,0.0,2024-07-03 09:46:40,Virtual,"Long Description, In this internship you will ...",120.0,2024-03-09 16:00:00,Career Automation 1713529462526,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ..."
5728,Opportunity#0000000010ZZ02VAKM6D63J357,Competition,MBBBCXF,2023-11-14 22:13:20,USD,30.0,weeks,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,NaN,0.0,2024-03-09 16:00:00,Virtual,"Long Description, In this internship you will ...",120.0,2023-11-14 22:13:20,Single Competition Automation 1699002657300,NaN,NaN,"Short Description, Explore hands-on defensive ..."
5729,Opportunity#0000000010XFNENX1PXV57SW74,Internship,I1DUNTK,2025-10-09 08:53:20,INR,1.0,months,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,0.0,2025-10-09 08:53:20,NaN,Long DescriptionLong DescriptionLong Descripti...,0.0,2025-10-09 08:53:20,Email one day,Role,NaN,Short DescriptionShort DescriptionShort Descri...

Insights:
The cleaned dataset consists of 5,730 records and 20 features, representing various opportunities along with their categories, duration, fees, locations, descriptions, and related metadata. The initial inspection confirms that the dataset has been successfully loaded and is ready for exploratory analysis.

### Business Insight: Dataset Composition
- The presence of **5,730 records** indicates a substantial database of opportunities.
- However, with only **20 features**, the data is relatively sparse in terms of behavioral tracking.
- The metadata suggests a platform-based ecosystem focusing on varied engagement types (Internships, Careers, etc.).

**Dataset Structure**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5730 entries, 0 to 5729
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   opportunity_id       5730 non-null   object
 1   category             5727 non-null   object
 2   code                 5729 non-null   object
 3   created_at           5726 non-null   datetime64[ns]
 4   currency_type        5387 non-null   object
 5   duration             5721 non-null   float64
 6   duration_type        5725 non-null   object
 7   fee                  5726 non-null   float64
 8   image_link           5723 non-null   object
 9   is_archived          525 non-null    float64
 10  is_auto_approve      5727 non-null   float64
 11  last_date_to_apply   5726 non-null   datetime64[ns]
 12  location             4275 non-null   object
 13  long_description     5386 non-null   object
 14  microscholarship     5725 non-null   float64
 15  modified_at          5726 non-null   datetime64[ns]
 16  name                 5730 non-null   object
 17  role                 1893 non-null   object
 18  role_responsibility  1079 non-null   object
 19  short_description    5730 non-null   object
dtypes: datetime64[ns](3), float64(5), object(12)
memory usage: 895.4+ KB

**Data Type Summary**

In [ ]:
df.dtypes

opportunity_id                 object
category                       object
code                           object
created_at             datetime64[ns]
currency_type                  object
duration                      float64
duration_type                  object
fee                           float64
image_link                     object
is_archived                   float64
is_auto_approve               float64
last_date_to_apply     datetime64[ns]
location                       object
long_description               object
microscholarship              float64
modified_at            datetime64[ns]
name                           object
role                           object
role_responsibility            object
short_description              object
dtype: object

**Missing Value Analysis**

In [ ]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing = missing.sort_values(
    by="Missing Values",
    ascending=False
)

missing

                     Missing Values  Percentage
is_archived                    5205   90.837696
role_responsibility            4651   81.169284
role                           3837   66.963351
location                       1455   25.392670
long_description                344    6.003490
currency_type                   343    5.986038
duration                          9    0.157068
image_link                        7    0.122164
microscholarship                  5    0.087260
duration_type                     5    0.087260
fee                               4    0.069808
created_at                        4    0.069808
modified_at                       4    0.069808
last_date_to_apply                4    0.069808
category                          3    0.052356
is_auto_approve                   3    0.052356
code                              1    0.017452
opportunity_id                    0    0.000000
name                              0    0.000000
short_description                 0    0.000000

### Business Insight: Data Quality & Governance
- **Critical Data Gaps**: `is_archived` (90% missing) and `role_responsibility` (81% missing) suggest that historical tracking or detailed role definitions are either optional or poorly captured during intake.
- **Location Data**: 25% of records are missing location data, which is a significant hurdle if the business model relies on geographic targeting.
- **Recommendation**: Implement mandatory fields for role responsibilities to improve the value proposition for applicants.

**Duplicate Analysis**

In [ ]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

**Summary Statistics**

In [ ]:
df.describe()

,created_at,duration,fee,is_archived,is_auto_approve,last_date_to_apply,microscholarship,modified_at
count,5726,5721.000000,5726.000000,525.000000,5727.00000,5726,5725.000000,5726
mean,2024-06-17 05:11:57.708697088,24.536095,57.454942,0.731429,0.14161,2024-04-05 20:58:01.103737088,175.660437,2024-07-20 01:01:43.527768064
min,2022-08-08 23:06:40,0.000000,0.000000,0.000000,0.00000,1970-01-01 00:00:00,0.000000,2023-03-28 10:40:00
25%,2023-11-14 22:13:20,12.000000,0.000000,0.000000,0.00000,2023-11-14 22:13:20,100.000000,2023-11-14 22:13:20
50%,2024-03-09 16:00:00,30.000000,0.000000,1.000000,0.00000,2024-07-03 09:46:40,120.000000,2024-03-09 16:00:00
75%,2025-02-19 21:20:00,30.000000,0.000000,1.000000,0.00000,2025-02-19 21:20:00,120.000000,2025-02-19 21:20:00
max,2026-05-28 20:26:40,359.000000,200000.000000,1.000000,1.00000,2027-12-28 13:20:00,50000.000000,2026-05-28 20:26:40
std,NaN,16.590264,2792.117561,0.443639,0.34868,NaN,832.732341,NaN

### Business Insight: Financial & Duration Profiles
- **Pricing Strategy**: The median `fee` is **0**, indicating that the majority of opportunities are free to access. The maximum fee of **200,000** is an extreme outlier and likely represents a high-end course or a data entry error.
- **Microscholarships**: Most scholarships hover around the **120 USD** mark. This suggests a standardized small-incentive model rather than high-value financial grants.

**Unique Values**

In [ ]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

opportunity_id: 5730 unique values
category: 10 unique values
code: 5728 unique values
created_at: 13 unique values
currency_type: 3 unique values
duration: 102 unique values
duration_type: 6 unique values
fee: 101 unique values
image_link: 3770 unique values
is_archived: 2 unique values
is_auto_approve: 2 unique values
last_date_to_apply: 19 unique values
location: 3 unique values
long_description: 894 unique values
microscholarship: 157 unique values
modified_at: 11 unique values
name: 5570 unique values
role: 429 unique values
role_responsibility: 88 unique values
short_description: 838 unique values

**Categorical Overview**

In [ ]:
categorical = df.select_dtypes(include='object').columns

for col in categorical:
    print("\n", "="*60)
    print(col)
    print(df[col].value_counts().head(10))

 ============================================================
opportunity_id
opportunity_id
Opportunity#0000000010XFNENX1PXV57SW74    1
Opportunity#000000000GBD0AX3Z6VYRG7R75    1
Opportunity#0000000010Z7R1E4W9MHYSV18K    1
Opportunity#0000000010ZYYDKE48S4PPGPST    1
Opportunity#0000000010T7874N5KKFCKABH2    1
Opportunity#0000000010T5S4C2RNYA96ZS9T    1
Opportunity#0000000010T5PSE0372ZVNM16C    1
Opportunity#0000000010J6VNJSMXND8P727Q    1
Opportunity#0000000010T5K3P9D4646RE03X    1
Opportunity#0000000010HMD373NWBTC9V2SY    1
Name: count, dtype: int64

 ============================================================
category
category
Internship       1591
Career           1087
Competition       734
Course            632
Event             622
Engagement        459
Masterclass       400
Jobsimulation     198
Program             2
Xploreu             2
Name: count, dtype: int64

 ============================================================
code
code
IZ18WQO    2
ISF9N6X    1
IBJ242V    1
MI8DSTC    1
IIKLIA3    1
IX810XA    1
IUSV4YK    1
MQADZQ7    1
ICJOCHP    1
MQBMSUF    1
Name: count, dtype: int64

 ============================================================
currency_type
currency_type
USD    4698
INR     355
EUR     334
Name: count, dtype: int64

 ============================================================
duration_type
duration_type
weeks      4286
months      513
hours       371
days        369
minutes     144
years        42
Name: count, dtype: int64

 ============================================================
image_link
image_link
https://excelerateuserprofile.s3.ap-south-1.amazonaws.com/opportunity_Images/Improved-career-planning-and-development-for-your-employees.png      1609
https://smsprofile.s3.ap-south-1.amazonaws.com/2.png                                                                                                55
https://smsprofile.s3.ap-south-1.amazonaws.com/CS.png                                                                                               25
test                                                                                                                                                22
img                                                                                                                                                 20
https://excelerateuserprofile.s3.ap-south-1.amazonaws.com/opportunity_Images/Cyber+security.jpg                                                     16
https://excelerate-profile-dev.s3.ap-south-1.amazonaws.com/WebsiteImageFiles/Opportunity/Opportunity_0000000010CEH57KPW0NJM22XP_image_link.png      14
image                                                                                                                                               12
Image of the Opportunity                                                                                                                            11
https://globalshala-iam.ml:81/assets/media/logos/excelerate_icon.png                                                                                 9
Name: count, dtype: int64

 ============================================================
location
location
Work From Home    2356
Virtual           1918
Kolkata              1
Name: count, dtype: int64

 ============================================================
long_description
long_description
Long Description, In this internship you will be in the role of a Cyber Defense Analyst at GlobalShala to serve our client Cisco, and will help to set up a virtualization environment for threat assessments testing and understanding different attack vectors. By the end of the internship the goal is to create a Virtual Machine (VM) that has the security tools and information security controls so it may be used throughout the organisation.    3501
Long Description                                                                                                                                                                                                                                                                                                                                                                                                                                             179
Long                                                                                                                                                                                                                                                                                                                                                                                                                                                         118
Short Description                                                                                                                                                                                                                                                                                                                                                                                                                                            118
long                                                                                                                                                                                                                                                                                                                                                                                                                                                          93
Long Long Long Long Description                                                                                                                                                                                                                                                                                                                                                                                                                               77
test                                                                                                                                                                                                                                                                                                                                                                                                                                                          60
long description                                                                                                                                                                                                                                                                                                                                                                                                                                              26
ok                                                                                                                                                                                                                                                                                                                                                                                                                                                            14
abcd                                                                                                                                                                                                                                                                                                                                                                                                                                                          12
Name: count, dtype: int64

 ============================================================
name
name
Secrets To Operational Excellence Course     11
Auto                                          6
Test                                          5
Linked UP: The LinkedIn Makeover Workshop     5
Opportunity name                              5
test                                          5
Ethical hacking                               4
Ea et dolore ratione                          4
Opportunity name Assignment Review            3
Asperiores sed corpo                          3
Name: count, dtype: int64

 ============================================================
role
role
Manager       720
Role          284
intern         93
Tester         64
manager        37
internship     29
role           26
Test           22
Intern         20
tester         18
Name: count, dtype: int64

 ============================================================
role_responsibility
role_responsibility
Testing and debugging                                                                                                                                                        879
Managing Teaching Head                                                                                                                                                        51
Testing and debugging1.Analyzing user requirements and translating them into technical specifications. 2.Designing, coding, testing, and debugging software applications.     15
Testing                                                                                                                                                                       14
Roles and Responsibility                                                                                                                                                      13
Manager                                                                                                                                                                        6
manager                                                                                                                                                                        4
testing application                                                                                                                                                            4
Tester                                                                                                                                                                         4
test                                                                                                                                                                           4
Name: count, dtype: int64

 ============================================================
short_description
short_description
Short Description, Explore hands-on defensive hacking techniques by understanding the concept of ?blue teams,? different attack vectors, brute force, denial of service, scans, backdoor attacks, and ot    3893
Short Description                                                                                                                                                                                            424
Short                                                                                                                                                                                                        106
short                                                                                                                                                                                                         90
test                                                                                                                                                                                                          55
short description                                                                                                                                                                                             30
Short DescriptionShort DescriptionShort Description                                                                                                                                                           17
SHort                                                                                                                                                                                                         16
Short DescriptionShort DescriptionShort DescriptionShort Description                                                                                                                                          15
abc                                                                                                                                                                                                           14
Name: count, dtype: int64

**Numerical Feature Analysis**

In [ ]:
numerical_cols = ['duration', 'fee', 'microscholarship']

df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
duration,5721.0,24.536095,16.590264,0.0,12.0,30.0,30.0,359.0
fee,5726.0,57.454942,2792.117561,0.0,0.0,0.0,0.0,200000.0
microscholarship,5725.0,175.660437,832.732341,0.0,100.0,120.0,120.0,50000.0

In [ ]:
stats = pd.DataFrame({
    'Mean': df[numerical_cols].mean(),
    'Median': df[numerical_cols].median(),
    'Mode': df[numerical_cols].mode().iloc[0],
    'Std Dev': df[numerical_cols].std(),
    'Minimum': df[numerical_cols].min(),
    'Maximum': df[numerical_cols].max(),
    'Skewness': df[numerical_cols].skew()
})

stats

,Mean,Median,Mode,Std Dev,Minimum,Maximum,Skewness
duration,24.536095,30.0,30.0,16.590264,0.0,359.0,4.150921
fee,57.454942,0.0,0.0,2792.117561,0.0,200000.0,66.426557
microscholarship,175.660437,120.0,120.0,832.732341,0.0,50000.0,40.327014

**Categorical Feature Analysis**

In [ ]:
categorical_cols = [
    'category',
    'location',
    'currency_type',
    'duration_type',
    'role',
    'is_archived',
    'is_auto_approve'
]
for col in categorical_cols:
    print("="*60)
    print(col)
    print(df[col].value_counts())

============================================================
category
category
Internship       1591
Career           1087
Competition       734
Course            632
Event             622
Engagement        459
Masterclass       400
Jobsimulation     198
Program             2
Xploreu             2
Name: count, dtype: int64
============================================================
location
location
Work From Home    2356
Virtual           1918
Kolkata              1
Name: count, dtype: int64
============================================================
currency_type
currency_type
USD    4698
INR     355
EUR     334
Name: count, dtype: int64
============================================================
duration_type
duration_type
weeks      4286
months      513
hours       371
days        369
minutes     144
years        42
Name: count, dtype: int64
============================================================
role
role
Manager                                720
Role                                   284
intern                                  93
Tester                                  64
manager                                 37
                                      ...
Et deleniti non a ab                     1
efsdc                                    1
Velit culpa dolore                       1
%22placeholder%22: %22Role/Title%22      1
Innovation Consultantantant              1
Name: count, Length: 429, dtype: int64
============================================================
is_archived
is_archived
1.0    384
0.0    141
Name: count, dtype: int64
============================================================
is_auto_approve
is_auto_approve
0.0    4916
1.0     811
Name: count, dtype: int64

### Business Insight: Market Segmentation
- **Product-Market Fit**: `Internships` and `Careers` dominate the platform, making up roughly **47%** of the total volume.
- **Work Culture**: The dominance of `Work From Home` and `Virtual` locations (nearly 100% of defined locations) positions this as a remote-first platform, which is highly attractive to the modern workforce but lacks physical regional footprints.

**Date Analysis**

In [ ]:
date_cols = ['created_at', 'modified_at', 'last_date_to_apply']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

In [ ]:
df['Creation Year'] = df['created_at'].dt.year
df['Creation Month'] = df['created_at'].dt.month_name()

df[['Creation Year','Creation Month']].head()

   Creation Year Creation Month
0         2022.0         August
1         2022.0         August
2         2024.0          March
3         2022.0       December
4         2022.0         August

In [ ]:
df.groupby('Creation Year').size()

Creation Year
2022.0      25
2023.0    2123
2024.0    2127
2025.0     895
2026.0     556
dtype: int64

### Business Insight: Growth Velocity
- **Expansion**: There is a massive jump in activity from **2022 (25 records)** to **2023 (2,123 records)**. This indicates a successful scaling phase or a major migration of data onto the platform in 2023.
- **Forward Planning**: Data for **2025** and **2026** indicates that the platform maintains a pipeline of long-term scheduled opportunities.

**Text Feature Analysis**

In [ ]:
text_columns = [
    'short_description',
    'long_description',
    'role_responsibility'
]

for col in text_columns:
    print(col)
    print(df[col].str.len().describe())

short_description
count    5730.000000
mean      148.675916
std        81.433701
min         1.000000
25%        57.000000
50%       200.000000
75%       200.000000
max       744.000000
Name: short_description, dtype: float64
long_description
count    5386.000000
mean      318.976606
std       242.833689
min         1.000000
25%        24.000000
50%       440.000000
75%       440.000000
max      4784.000000
Name: long_description, dtype: float64
role_responsibility
count    1079.000000
mean       24.088044
std        30.423612
min         1.000000
25%        21.000000
50%        21.000000
75%        21.000000
max       536.000000
Name: role_responsibility, dtype: float64

**Logical Consistency Checks**

In [ ]:
df[df['fee'] < 0]

Empty DataFrame
Columns: [opportunity_id, category, code, created_at, currency_type, duration, duration_type, fee, image_link, is_archived, is_auto_approve, last_date_to_apply, location, long_description, microscholarship, modified_at, name, role, role_responsibility, short_description, Creation Year, Creation Month]
Index: []

[0 rows x 22 columns]

In [ ]:
df[df['duration'] <= 0]

,opportunity_id,category,code,created_at,currency_type,duration,duration_type,fee,image_link,is_archived,...,location,long_description,microscholarship,modified_at,name,role,role_responsibility,short_description,Creation Year,Creation Month
1433,Opportunity#0000000010VJC7AS6GQAR6PRZE,Competition,M9SYBFY,2023-03-28 10:40:00,USD,0.0,weeks,0.0,https://api.badgr.io/public/badges/KOX1wTa6QkG...,1.0,...,Virtual,Auto Approval Opportunity,1110.0,2023-07-22 04:26:40,Team B Comp. AA,NaN,NaN,Auto Approval Opportunity,2023.0,March
3615,Opportunity#0000000010DRH1Q3QYN9WYH4QF,Internship,IA2SX9X,2023-03-28 10:40:00,EUR,0.0,weeks,65.0,Hic officia id culpa,1.0,...,Virtual,Consectetur omnis s,66.0,2023-07-22 04:26:40,Qui iure quo tempora,Est voluptas conseq,NaN,Ad velit quam facere ut voluptatem debitis qui...,2023.0,March
4796,Opportunity#0000000010NMCAB55DP4PWDY6D,Internship,IQMYKLI,2023-03-28 10:40:00,USD,0.0,hours,0.0,https://encrypted-tbn0.gstatic.com/images?q=tb...,1.0,...,Virtual,dfgfdg,250.0,2023-07-22 04:26:40,Testing Checks by MS,Tarinee,NaN,bgfdgh,2023.0,March

In [ ]:
df[df['last_date_to_apply'] < df['created_at']]

,opportunity_id,category,code,created_at,currency_type,duration,duration_type,fee,image_link,is_archived,...,location,long_description,microscholarship,modified_at,name,role,role_responsibility,short_description,Creation Year,Creation Month
2,Opportunity#0000000010ZFE0ZS22FA3Q62R4,Career,A8848RT,2024-03-09 16:00:00,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,Work From Home,NaN,0.0,2024-03-09 16:00:00,Careerwishlist Automation 1710333189352,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",2024.0,March
8,Opportunity#0000000010YHJCSGAKECPBFQ65,Course,UOU4P4A,2025-02-19 21:20:00,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,Virtual,NaN,0.0,2025-02-19 21:20:00,Course Automation 1740727622332,NaN,NaN,"Short Description, Explore hands-on defensive ...",2025.0,February
9,Opportunity#0000000010ZNX2EXET8MGC9F7B,Career,AS0YA59,2023-11-14 22:13:20,NaN,30.0,weeks,0.0,https://excelerateuserprofile.s3.ap-south-1.am...,NaN,...,Virtual,NaN,0.0,2023-11-14 22:13:20,Careerwishlist Automation 1701751082558,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",2023.0,November
96,Opportunity#0000000010FCVD65SWH9EDEREB,Engagement,NTN0YLJ,2026-02-02 02:40:00,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,Work From Home,NaN,0.0,2026-02-02 02:40:00,Engagement Automation 1768381468122,NaN,NaN,"Short Description, Explore hands-on defensive ...",2026.0,February
108,Opportunity#000000001008KA64Q5B4SYZAVE,Career,AZ5ZM69,2024-03-09 16:00:00,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,Work From Home,NaN,0.0,2024-03-09 16:00:00,Careerwishlist Automation 1714724256391,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",2024.0,March
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,Opportunity#0000000010ZZTEHSZVVQED5M1V,Engagement,N0KTMZ0,2025-02-19 21:20:00,EUR,9.0,hours,0.0,Sequi rerum accusant,1.0,...,NaN,Magni quas est quide,3.0,2023-07-22 04:26:40,Engagement Role,NaN,NaN,Dolor consequatur do repellendus Quae ea nihil...,2025.0,February
5702,Opportunity#0000000010YQC60E3FMCXXQTGN,Event,ELK6FP2,2023-11-14 22:13:20,NaN,30.0,weeks,1.0,https://excelerateuserprofile.s3.ap-south-1.am...,NaN,...,NaN,NaN,0.0,2023-11-14 22:13:20,Event Automation 1703237359996,NaN,NaN,"Short Description, Explore hands-on defensive ...",2023.0,November
5718,Opportunity#0000000010ZKXH1KJTS4K7D9P2,Course,U2XAZV0,2025-10-09 08:53:20,INR,10.0,days,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,Virtual,test,100.0,2025-10-09 08:53:20,course master wishlist,NaN,NaN,test,2025.0,October
5719,Opportunity#0000000010TZF14AAWKD0WZPRE,Event,ECXEFC2,2024-03-09 16:00:00,NaN,30.0,weeks,1.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,NaN,NaN,0.0,2024-03-09 16:00:00,Event Automation 1709191993846,NaN,NaN,"Short Description, Explore hands-on defensive ...",2024.0,March
5724,Opportunity#0000000010ZTWDJSBCEW0V0JCM,Career,ARAS4MG,2024-10-27 03:33:20,NaN,30.0,weeks,0.0,https://excelerate-profile-dev.s3.ap-south-1.a...,NaN,...,NaN,NaN,0.0,2024-10-27 03:33:20,Careerwishlist Automation 1726570565298,NaN,Testing and debugging,"Short Description, Explore hands-on defensive ...",2024.0,October

### Business Insight: Operational Risks
- **Logical Inconsistency**: **361 records** show a `last_date_to_apply` that is *before* the `created_at` date. This represents a technical bug or poor data entry that could lead to poor user experience, as users might see expired opportunities the moment they are posted.

**Correlation Analysis**

In [ ]:
corr = df[numerical_cols].corr()

corr

                  duration       fee  microscholarship
duration          1.000000  0.023751         -0.015989
fee               0.023751  1.000000          0.240942
microscholarship -0.015989  0.240942          1.000000

**Outlier Verification**

In [ ]:
for col in numerical_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col)
    print("Outliers:", len(outliers))

duration
Outliers: 134
fee
Outliers: 1208
microscholarship
Outliers: 1641

### Business Insight: Outlier & Variability Management
- **Fee Skewness**: With 1,208 outliers in fees, the platform hosts a wide variety of economic tiers.
- **Scholarship Variance**: The high number of outliers in `microscholarship` (1,641) indicates that while there is a standard rate, there are significant "premium" or "specialty" incentives that may need distinct marketing strategies.

## Executive Summary & Final EDA Conclusion

### 1. Data Integrity & Governance
- **Significant Information Gaps**: With over **90% missing data in archiving** and **81% in role responsibilities**, the platform currently lacks the granular data needed for deep matching or historical trend analysis.
- **Technical Anomalies**: The discovery of **361 records** with application deadlines preceding their creation dates suggests an urgent need for backend validation logic to prevent user frustration.

### 2. Market Positioning
- **Core Strengths**: The platform has successfully carved out a niche in the **Internship and Career** segments, which together represent nearly half of all offerings.
- **Remote-First Identity**: The near-total dominance of **Virtual/Work From Home** locations positions the platform as a key player for remote engagement, though it limits growth in industries requiring a physical presence.

### 3. Economic Model
- **Incentive-Driven**: The business model leans heavily toward **free access** with standardized low-value **microscholarships (~$120)**. This suggests a high-volume, low-barrier-to-entry strategy designed to maximize student engagement.
- **High-End Outliers**: A small subset of high-fee and high-scholarship opportunities exists, which may require a segmented marketing approach to distinguish them from the standard free offerings.

### 4. Growth Trajectory
- The platform experienced an exponential **85x growth in listings** between 2022 and 2023. Maintaining this momentum will require improving data quality standards to ensure that the increased quantity of opportunities does not come at the cost of relevance and accuracy.